language: generic

addons:
    apt:
        packages:
            - g++-6
        sources:
            - ubuntu-toolchain-r-test
matrix:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          sudo: required
          env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
        - os: osx
          osx_image: xcode7.3
          compiler: clang
        - os: osx
          osx_image: xcode7.3
          language: ruby
          rvm: 2.3.1
          gemfile: tools/translator/Gemfile
          env: DOC_TEST_ONLY=1

before_install:
    - .travis/install.sh

branches:
    only:
        - develop

script:
    - .travis/run.sh
